#!/bin/bash
#SBATCH --nodes=6
#SBATCH --ntasks-per-node=2
#SBATCH --cpus-per-task=18

#SBATCH --time=24:00:00

#SBATCH --output=results/mpi_numa_sendrecv_O3_%j.out
#SBATCH --error=mpi_err.err

export OMP_PROC_BIND=close
export OMP_PLACES=cores

export OMP_NUM_THREADS=1
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 500 600 400
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 1000 1200 800
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 2000 2400 1600
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 4000 4800 3200
export OMP_NUM_THREADS=2
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 500 600 400
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 1000 1200 800
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 2000 2400 1600
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 4000 4800 3200
export OMP_NUM_THREADS=3
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 500 600 400
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 1000 1200 800
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 2000 2400 1600
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 4000 4800 3200
export OMP_NUM_THREADS=4
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 500 600 400
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 1000 1200 800
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 2000 2400 1600
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 4000 4800 3200
export OMP_NUM_THREADS=5
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 500 600 400
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 1000 1200 800
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 2000 2400 1600
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 4000 4800 3200
export OMP_NUM_THREADS=6
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 500 600 400
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 1000 1200 800
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 2000 2400 1600
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 4000 4800 3200
export OMP_NUM_THREADS=7
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 500 600 400
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 1000 1200 800
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 2000 2400 1600
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 4000 4800 3200
export OMP_NUM_THREADS=8
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 500 600 400
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 1000 1200 800
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 2000 2400 1600
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 4000 4800 3200
export OMP_NUM_THREADS=9
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 500 600 400
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 1000 1200 800
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 2000 2400 1600
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 4000 4800 3200
export OMP_NUM_THREADS=10
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 500 600 400
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 1000 1200 800
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 2000 2400 1600
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 4000 4800 3200
export OMP_NUM_THREADS=11
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 500 600 400
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 1000 1200 800
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 2000 2400 1600
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 4000 4800 3200
export OMP_NUM_THREADS=12
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 500 600 400
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 1000 1200 800
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 2000 2400 1600
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 4000 4800 3200
export OMP_NUM_THREADS=13
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 500 600 400
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 1000 1200 800
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 2000 2400 1600
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 4000 4800 3200
export OMP_NUM_THREADS=14
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 500 600 400
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 1000 1200 800
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 2000 2400 1600
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 4000 4800 3200
export OMP_NUM_THREADS=15
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 500 600 400
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 1000 1200 800
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 2000 2400 1600
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 4000 4800 3200
export OMP_NUM_THREADS=16
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 500 600 400
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 1000 1200 800
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 2000 2400 1600
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 4000 4800 3200
export OMP_NUM_THREADS=17
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 500 600 400
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 1000 1200 800
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 2000 2400 1600
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 4000 4800 3200
export OMP_NUM_THREADS=18
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 500 600 400
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 1000 1200 800
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 2000 2400 1600
mpirun --map-by numa ./wave_eq_2d_mpi_openmp_sendrecv_O3 5 6 4 4000 4800 3200
