#!/bin/bash
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=36

#SBATCH --time=24:00:00

#SBATCH --output=results/p1_%j.out
#SBATCH --error=mpi_err.err

export OMP_PROC_BIND=close
export OMP_PLACES=cores

export OMP_NUM_THREADS=1
./wave_eq_2d_mpi_openmp_isend 5 6 4 500 600 400
./wave_eq_2d_mpi_openmp_isend 5 6 4 1000 1200 800
./wave_eq_2d_mpi_openmp_isend 5 6 4 2000 2400 1600
./wave_eq_2d_mpi_openmp_isend 5 6 4 4000 4800 3200
./wave_eq_2d_mpi_openmp_isend_O3 5 6 4 500 600 400
./wave_eq_2d_mpi_openmp_isend_O3 5 6 4 1000 1200 800
./wave_eq_2d_mpi_openmp_isend_O3 5 6 4 2000 2400 1600
./wave_eq_2d_mpi_openmp_isend_O3 5 6 4 4000 4800 3200
