#!/bin/bash
# Пример запуска MPI приложения с использованием 72 ядер (два вычислительных узла)
# На вычислительных узлах включена Intel® Hyper-Threading эта технология позволяет обрабатывать на каждом ядре процессора два потокa. Данная технология используется, так как узлы параллельно могут задействоваться под задачи виртуализации.
# Реальное количество ядер на сервере 36, для расчётов доступно 4 сервера.
# 
# Количество потоков MPI. (должно быть больше или равно 72, но меньше или равно 144 )
#SBATCH -n 72 
#
# Количество ядер на узле, изменять значение не нужно.
#SBATCH --tasks-per-node=36 
#
# Ограничение времени выполнения задачи, например, 1 час.
#SBATCH --time=1:00:00

# Загрузка модулей.
module load openmpi4/openmpi4
module load gcc/gcc-7.4 

# Запуск программы MPI
mpirun ./mpi_program


#!/bin/bash

#SBATCH --nodes=2
#SBATCH --nodelist="vmnode38 vmnode39"

#SBATCH --ntasks=8
#SBATCH --ntasks_per_node=4
#SBATCH --tasks-per-node=36

#SBATCH --cpus-per-task=4

#SBATCH --time=24:00:00

#SBATCH --output=mpi%j.out
#SBATCH --error=mpi_err.err

export OMP_NUM_THREADS=8

mpirun ./mpi_program